version: "3.9"
services:
  bootstrap:
    build: ./backend
    image: zonemaster-backend
    volumes:
      - ./backend.conf.d:/etc/zonemaster:ro
    command: bootstrap
    profiles:
      - bootstrap
    depends_on:
      - postgres

  zonemaster-rpcapi:
    build: ./backend
    image: zonemaster-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend.conf.d:/etc/zonemaster:ro
    command: rpcapi
    depends_on:
      - postgres
    read_only: true

  zonemaster-agent:
    build: ./backend
    image: zonemaster-backend
    volumes:
      - ./backend.conf.d:/etc/zonemaster:ro
    command: agent
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
    read_only: true
    tmpfs:
      - /tmp

  zonemaster-gui:
    build: ./gui
    image: zonemaster-gui
    environment:
      ZONEMASTER_API_ENDPOINT: http://zonemaster-rpcapi:5000
    volumes:
      - ./gui.conf.d:/config:ro
    ports:
      - "8080:80"
    depends_on:
      - zonemaster-rpcapi
    read_only: true
    tmpfs:
      - /etc/nginx/conf.d
      - /var/cache/nginx
      - /var/run

  zonemaster-cli:
    build: ./cli
    image: zonemaster-cli
    profiles:
      - cli
    read_only: true

  postgres:
    image: postgres:12-alpine
    command: postgres -c shared_buffers=256MB -c max_connections=300
    environment:
        POSTGRES_USER: zonemaster
        POSTGRES_PASSWORD: zonemaster
        POSTGRES_DB: zonemaster
    read_only: true
    tmpfs:
      - /var/run/postgresql
