version: "3.9"
services:
  bootstrap:
    build: ./backend
    image: zonemaster-bakend
    volumes:
      - ./backend.conf.d:/etc/zonemaster:ro
    command: bootstrap
    profiles:
      - bootstrap
    depends_on:
      - postgres

  zonemaster-api:
    build: ./backend
    image: zonemaster-bakend
    ports:
      - "5000:5000"
    volumes:
      - ./backend.conf.d:/etc/zonemaster:ro
    command: api
    depends_on:
      - postgres

  zonemaster-agent:
    build: ./backend
    image: zonemaster-bakend
    volumes:
      - ./backend.conf.d:/etc/zonemaster:ro
    command: agent
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1

  zonemaster-gui:
    build: ./gui
    image: zonemaster-gui
    environment:
      ZONEMASTER_API_ENDPOINT: http://zonemaster-api:5000
    volumes:
      - ./gui.conf.d:/config:ro
    ports:
      - "8080:80"
    depends_on:
      - zonemaster-api

  zonemaster-cli:
    build: ./cli
    image: zonemaster-cli
    profiles:
      - cli

  postgres:
    image: postgres:12
    command: postgres -c shared_buffers=256MB -c max_connections=300
    environment:
        POSTGRES_USER: zonemaster
        POSTGRES_PASSWORD: zonemaster
        POSTGRES_DB: zonemaster
